### ISSUE TITLE
Working with files

### ISSUE THREAD

**Issue by GilAdirim** [msiemens/tinydb#102]
Hi,

Can a tinyDB record include files? I know that MongoDB uses BSON to store binary files, and was wondering if I can do the same with tinyDB.

Thanks!

**Comment by eugene-eeo** [comment]
Technically it's possible. However it depends on what you consider a file.

If you're talking about only the file path then yes, you can do it without going through any hoops. But if you are talking about the *content* of the file and you are working with binary files using the JSON storage you'd have to encode it in some ascii-only format, e.g. base64 so that the JSON library, working only with UTF8 can serialise it. Case in point:

```python
>>> from base64 import b64encode
>>> import json
>>> json.dumps({'a': b'a'})
...
TypeError: b'a' is not JSON serializable
>>> json.dumps({'a': b64encode(b'a').decode()})
'{"a": "YQ=="}'
```

Although for larger stuff it is not practical. You should [write a custom storage class](https://tinydb.readthedocs.io/en/latest/extend.html#write-a-custom-storage) that uses BSON or some format capable of handling binary data. Although if you insist on using the JSON storage, you should use [a custom middleware](https://tinydb.readthedocs.io/en/latest/extend.html#write-a-custom-middleware) that handles binary data automatically.

**Comment by GilAdirim** [comment]
Alright, that sounds like a good way to start.

Thanks!
