### ISSUE TITLE
how to implement tinyDB memory with server json?

### ISSUE THREAD

**Issue by faststare** [msiemens/tinydb#141]
let say I only have requests.get that read my entire data and I only have requests.put to write the whole data to overwrite the server data. can you give me some idea I how reconstruct or edit the tinydb to my needs? I tried to create a table extension but the init of tinyDB have .read within which will fail my custom storage. please help me.

PS: here's my current custom storage https://pastebin.com/8mi2mQKd but it failed to run due to _.read method in tinyDB itself.

**Comment by eugene-eeo** [comment]
Hi @faststare I've looked through your comment and code. From my understanding, you are trying to implement a storage class that will read data from the server when required using a HTTP GET request, and then save data by using HTTP PUT.

⚠️  **Warning** ⚠️ 

Firstly please *DO NOT* use this approach for anything serious because it does not work well. Assuming that what happens during the HTTP PUT is that you override the data on disk, writes from two instances of your program is not guaranteed to work every time. (i.e., you have a race condition in your hands).

For instance let's see what happens when you have two instances A and B running at the same time. The following is perfectly possible unless you have ~some locking mechanism in place~ (actually if you need this, most of the time you should use a Real DB™ instead):

1. A reads data from the server.
2. B reads data from the server.
3. A writes some data.
4. B writes some data.
5. The next read from the server does not include A's written data.

**Proceed at your own risk!**

Do you mean that your `.read` method raises an exception when ran? In that case if it makes sense, you need to return `None` so that TinyDB can do some initialisation (for bookkeeping purposes). So you should change it to:

```python
    def read(self):
        data = requests.get('localhost:8080/get/' + self.filename)
        try:
            return json.loads(data.text)
        except ValueError:
            return None
```

Also in your write method you have a syntax error. Most likely what you want to do in this case is (referring to the [Quickstart](http://docs.python-requests.org/en/master/user/quickstart/) documentation):

```python
    def write(self, data):
        requests.put('localhost:8080/get/' + self.filename, data=data)
```

**Comment by faststare** [comment]
@eugene-eeo  you solved my problem in one comment. thank you.
