### ISSUE TITLE
Would tinydb be better if we use JSON Lines format?

### ISSUE THREAD

**Issue by hieu-n** [msiemens/tinydb#162]
I just gave tinydb a try. One thing I noticed the format is like this:

`{"_default":{"1":{"a":1},"2":{"b":2}}}`

So it is likely that tinydb has to parse the entire object in memory. Have you considered JSON Lines format (http://jsonlines.org/examples/)?

For an example:
```
{"_default":{"1":{"a":1}}}
{"_default":{"2":{"b":2}}}
...
```

I haven't thought of all the cases, but the advantage is when doing search in a large database file, we can iterate over the file line by line instead of reading and parsing the entire file.

This is just an idea. Have a nice day!
Hieu

**Comment by Phuket2** [comment]
@hieu-n, I am still a beginner. But you could use TinyDB Storages [Docs here](http://tinydb.readthedocs.io/en/latest/extend.html) and do some test timing. I only mention if you are interested.  Would be interesting to see the result. Has the added advantage that TinyDB requires no changes.  Uses could choose to use your storage extension.

**Comment by msiemens** [comment]
@hieu-n That's an interesting approach. I haven't heard of JSON Lines so far and it seems intriguing. But there's a big downside to this: you can't easily look up single documents by ID as we can right now. Also, if we only parse single lines, we'd have to do a bunch of newline seeking when iterating over documents. We'd basically always have to start parsing until we reach a newline and only then know where the next document starts.

Anyway, it would be am interesting experiment to see if one can create a TinyDB-like database using this approach 🙂

**Comment by eugene-eeo** [comment]
@hieu-n we can't really use JSON lines because it's hard to modify the first few lines (since you'd have to rewrite the whole thing!), but we could do with something like an [AOF](https://redis.io/topics/persistence) similar to more performant/"real" databases. An idea I have is that:

1. Each table has it's own AOF
2. Each document is stored on it's own line
3. Each table also has it's own metadata for each record, `{doc_id: doc_info}`
    - `doc_info.deleted`: boolean value, true if document is deleted
    - `doc_info.new`: 0 if document has not been modified, else it's the index in the file that we need to seek to find the newer document.

Here's the trick: values of `doc_info.new` do _not_ need to be updated since it's an AOF and the file is never going to be overwritten, just appended to. So for example to iterate over the database:

```
for line in file:
    doc = json.loads(line)
    info = metadata[doc.doc_id]
    if info.deleted:
        continue
    if info.new != 0:
        doc = handle_modified(info, file)
    yield doc
```

where `handle_modified` is:

```
def handle_modified(info, file):
    old_pos = file.tell() # gives us the current position in the file
    while info.new != 0:
        skip = info.new
        file.seek(skip)
        doc = json.loads(file.readline())
        info = metadata[doc.doc_id]
    file.seek(old_pos)
    return doc
```

Now of course the code you will write isn't that simple (buffered IO etc) but it could be done. Also if you take the AOF path then most likely TinyDB can allow for multi readers/writers, since we can synchronise writing so that each writer gets to write some number of lines before the next writer does so. For reading new data we can just stop reading when we find that the line is malformed.
