### ISSUE TITLE
Table instance returns results, which were removed from another instance

### ISSUE THREAD

**Issue by wuarmin** [msiemens/tinydb#179]
Hello.
tinydb is great! But I have one issue. I'm wrapping tinydb with a repository approach:
```python
class ScheduleRepository:

  def __init__(self):
    self.db = TinyDB('schedules_db.json')
    self.table = self.db.table('schedules')

  def find(self, id):
    result = self.table.search(Query().id == id)
    return Schedule(**result[0]) if len(result) > 0 else None

  def create(self, schedule):
    self.table.insert({
      'id': schedule.id, 
      'next_start': schedule.next_start.strftime('%Y-%m-%dT%H:%M:%S.%f'),
      'next_stop': schedule.next_stop.strftime('%Y-%m-%dT%H:%M:%S.%f')
    })

  def delete(self, schedule):
    self.table.remove(where('id') == schedule.id)
````
While testing, I used two instances of ScheduleTepository and encountered following behavior:
```python
...
repo1 = ScheduleRepository()
repo2 = ScheduleRepository()
repo1.create(object)
repo2.find(1) # returns the created object
repo1.delete(object)
repo2.find(1) # still returns the created object.
```
If the first repo2.find(1) is commented out the second returns None. So, obviously, it is a caching behavior. 
Is there a way to solve this issue. Should I use a singleton?
Thx

**Comment by msiemens** [comment]
Hey, thanks for reporting this! The issue is the query cache. We cache the results of queries as long as the data doesn't change. Now, we store the query cache _per table instance_. You have two table instances and if you delete an element in one, the other query cache wont't get updated.

I'm really not sure how we could solve this (besides making the documentation say that such behavior is unsafe). We would need to have a global query cache instead of a per table one. We'd have to separate the queries we cache by table name. But the user might have multiple database instances with different files which still share table names, so we would have to account for the storage source as well which isn't supported in the current design. I think, I'll have to think about this for some time…

**Comment by eugene-eeo** [comment]
@msiemens A short term fix is maybe issue warnings when we detect that the same arguments are given in the ``__init__`` method? We can't cache on a filename-basis as well since some backends don't rely on a filepath, etc. This is a hard problem because without coming up with a convoluted cache protocol we can't really solve it nicely.

**Comment by msiemens** [comment]
Well, having the same arguments _may_ be an issue, but not necessarily. A `MemoryStorage` for example always creates separate storages for each new instance even when called with the same arguments… At the moment my preferred solution would be to discourage sharing the file between multiple storage instances in the documentation…

**Comment by wuarmin** [comment]
@msiemens Thank you for your response. :smiley:  
I think if people know this behavior, they can live with it. I can. Maybe we should add it to the readme? What do you think about it?

Furthermore: Is it possible to disable the query-cache?

thanks

**Comment by eugene-eeo** [comment]
@wuarmin When you create/access a table, use `db.table('table-name', cache_size=0)`, the default cache size is 10, but you're right, I think we need to add an option to disable the query cache. Would you like to write a PR for that?

**Comment by wuarmin** [comment]
@eugene-eeo Ok, sounds good!
Yes I'll provide some.

**Comment by msiemens** [comment]
> When you create/access a table, use `db.table('table-name', cache_size=0)`

By the way, this wouldn't disable the query cache but rather make it infinite in size…

**Comment by msiemens** [comment]
I've now added a note to the documentation that having multiple TinyDB instances pointing to the same data may cause issues that can be resolved by disabling the query cache. Can we close this now? @wuarmin

**Comment by wuarmin** [comment]
@msiemens  Ok, thanks.
Yes I will close it.
