### ISSUE TITLE
Unary operator needs to be in parens?

### ISSUE THREAD

**Issue by jamesshannon** [msiemens/tinydb#243]
Does the unary operator need to be in parenthesis?

I tried several versions of `servers.search(~ q.turned_down == 'True')` and got the following error:

```
Traceback (most recent call last):
 ......
    return sorted(servers.search(~ q.turned_down == 'True'))
TypeError: bad operand type for unary ~: 'Query'
```

Eventually `servers.search(~ (q.turned_down == 'True'))` worked. 

I'm using py3.7.0.

I've never understood the black magic of search queries as arguments, so maybe I'm missing something...

**Comment by msiemens** [comment]
Hey @jamesshannon 

Unfortunately, Python's operator precedence isn't quite optimal for the TinyDB query syntax. It's not possible to overload Python's `not` operator, so we're left with `~`. But – `~` has higher priority than `==`, so `servers.search(~ q.turned_down == 'True')` is parsed by Python as `servers.search((~q.turned_down) == 'True')` – which is not quite what we wanted. That's why it's required to use paranthesis around the argument that is negated as you correctly found out.

Do you think this could be explained better in the documentation?

**Comment by msiemens** [comment]
Yes, I think this should be noted in the docs. For now I've at least fixed the example in the docs, but there should be a paragraph explaning the general behavior.

**Comment by eugene-eeo** [comment]
@msiemens ideally there should be a link to the operator precedence tables as well.
