### ISSUE TITLE
Are there any 'commit' or 'flush' operations? Seems the search result is not always corret if we do some updates in class

### ISSUE THREAD

**Issue by Bestoa** [msiemens/tinydb#260]
Hi,

Here is my test code, the line 17 and line 19 will print different result, obviously the output of line 17 is incorrect. But if you use db.all(), the result is OK. So I think the bug comes from the search, tks
```
from tinydb import TinyDB, Query

class test:
    def __init__(self):
        self.db = TinyDB('test')
        self.query = Query()

t = test()
t.db.insert({'test1': 1, 'test2': 2})


db = TinyDB('test')
query = Query()

print(db.search(query['test2'] == 2))
t.db.update({'test1': 3}, query['test2'] == 2)
print(db.search(query['test2'] == 2))
db = TinyDB('test')
print(db.search(query['test2'] == 2))
```
List the output here:
[{'test1': 1, 'test2': 2}]
[{'test1': 1, 'test2': 2}]
[{'test1': 3, 'test2': 2}]

B & R

**Comment by msiemens** [comment]
Hey @Bestoa,

TinyDB files shouldn't be opened multiple times at once in the same Python process (see the [note in the docs](https://tinydb.readthedocs.io/en/latest/usage.html#remarks-on-storage)). First, there is a query cache, which in this case seems to return an old result. One could fix that by calling `db.clear_cache()` before querying. But second, writing from multiple TinyDB instances will *probably* screw the contents of the database up at some point, which is why this is discouraged to do.

Hope this clears it up a little.

**Comment by eugene-eeo** [comment]
@Bestoa I remember there being an option to disable the query cache in the table class too, that probably is the best option if you want to use multiple instances. Probably something along the lines of:

```python
from tinydb import TinyDB, Table

class CustomTable(Table):
    def __init__(self, *args, **kwargs):
        kwargs['cache_size'] = 0
        Table.__init__(self, *args, **kwargs)

db = TinyDB('test.json')
db.table_class = CustomTable
```

**Comment by Bestoa** [comment]
Hi @msiemens,

Thank you for your clarification. I just meet this when I writing the unit test, will never do such thing in applications

Thanks
