### ISSUE TITLE
Maybe deprecate ujson?

### ISSUE THREAD

**Issue by msiemens** [msiemens/tinydb#263]
[`ujson`'s last commit](https://github.com/esnme/ultrajson/commits/master) was in March 2017, it seems unmaintained, it seems to leak memory in some circumstances and is not drop-in compatible with Python's `json`.  I think we shouldn't advise its use any more and consider removing official support for it in a future version and deprecate it for now.

What do you think @eugene-eeo?

**Comment by msiemens** [comment]
Maybe [python-rapidjson](https://github.com/python-rapidjson/python-rapidjson) could serve as an alternative if needed

**Comment by jayvdb** [comment]
While it isnt maintained in the repo, distros have been applying patches.

I would recommend using mujson, except it doesn't have a test suite yet. See https://github.com/mattgiles/mujson/issues/2

**Comment by eugene-eeo** [comment]
@msiemens yeah, I think dropping support for it officially would be better, since we don't really know what's going on with ujson. If needed, users can write their own storage layer over ujson. The newer kid on the block seems to be [`orjson`](https://github.com/ijl/orjson) but I'm not sure whether it offers comparable features to Python's stdlib json.

**Comment by kipkoan** [comment]
@msiemens - the website still recommends using ujson to improve performance: https://tinydb.readthedocs.io/en/v1.3.0/limitations.html

**Comment by msiemens** [comment]
@kipkoan In the latest version of the documentation (https://tinydb.readthedocs.io/en/latest/), the mention of `ujson` has been removed
