### ISSUE TITLE
Is Table#purge() replaced by Table#truncate()?

### ISSUE THREAD

**Issue by desmondlzy** [msiemens/tinydb#294]
Hi! I am using tinydb version 3.15.1, python 3.6.2

When I followed your doc and tried to invoke `purge_table` of a database instance, it gives an `AttributeError`

```
File "C:\Users\lzy71\MyProject\timewalk-core\timewalk\database\adapter.py", line 58, in write_session
    self.database.purge_table("mytable")
  File "C:\Users\lzy71\MyProject\timewalk-core\timewalk\packages\tinydb\database.py", line 250, in __getattr__
    return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'purge_table'
```

I switched to call the `purge` method on table instance and similar errors occurred again. So I go to the source code and find a `truncate` method that functions as `purge`. After I change to `truncate`,, problem solved.

So is your documentation out of date? I even cannot get any result after searching 'trancate' in the doc.

Thank you.

**Comment by msiemens** [comment]
Hey! Something must have gotten mixed up with your TinyDB version. TinyDB 3.15.1 uses `db.purge_tables()`, `db.purge_table(name)` and `table.purge()`, see the source code in https://github.com/msiemens/tinydb/blob/c8aefe9ad7b9befeb4e85f112890698ae5e72bc6/tinydb/database.py#L219-L238. TinyDB v3.15.1 does not contain a `truncate` method.

The current development version on `master` on the other hand is the work-in-progress version of TinyDB 4 which switched to using `db.drop_tables()`, `db.drop_table(name)` and `table.truncate()` to clear data.

Seems like you got the development version instead of v3.15.1 somehow…

**Comment by desmondlzy** [comment]
Thanks for your reply. I see the problem here... going to close this.

The source code I downloaded is on `master`, not `v3`. And I thought I was using v3.15.1 because I saw the information in `version.py`. So perhaps `version.py` on `master` shall be updated to avoid possible confusion caused?
