### ISSUE TITLE
Small Question: Read the source code and use the problems found.

### ISSUE THREAD

**Issue by daidai21** [msiemens/tinydb#338]
Hello,

Excuse me. I have some questions to ask you.

#### 1. Do you need to add multiplication, division and remainder operations in operations module?

like this:
```py
def multiplication(field, n):
    def transform(doc):
        doc[field] *= n

    return transform

...
```

#### 2. why `update` and `pop` methods of `tinydb.utils.FrozenDict` write like this? Is it because `update` and `clear` are different?

```py
    update = _immutable
    pop = _immutable
```

[about link](https://github.com/msiemens/tinydb/blob/master/tinydb/utils.py#L109-L120)

**Comment by eugene-eeo** [comment]
Hi,

1. I'm not sure why we didn't add them, I believe it's because we want to keep the API small and these operations are easily implementable anyways, in a project one can always write them as needed.

2. I'm not sure why it isn't written like this, I think it should be written like this as well. Actually more on this, we should subclass `OrderedDict` since in Python 3.5+ (at least CPython, AFAIK) `dict`s are sorted, but I'm not sure about PyPy or Jython. Using `OrderedDict` should let the runtime do the optimisation for us, so we don't have to add a `sorted` call when hashing:

```
    def __hash__(self):
        # Calculate the has by hashing a tuple of all dict items
        return hash(tuple(self.items()))
```

3. Indeed this is true.

You can maybe make a PR with those code fixes.

cc @msiemens

**Comment by daidai21** [comment]
I find Question 3 and test case are difference.
* [test_lru_cache()](https://github.com/msiemens/tinydb/blob/master/tests/test_utils.py#L6-L19)
* [test_lru_cache_get()](https://github.com/msiemens/tinydb/blob/master/tests/test_utils.py#L32-L40)

**Comment by daidai21** [comment]
`LRUCahe.set()` test case not fully.
Moving the Key to the front and back will pass the test case.

**Comment by msiemens** [comment]
> 1. Do you need to add multiplication, division and remainder operations in operations module?

@eugene-eeo is correct: I felt like one has to make a cut somewhere and I wanted to include some base operations but also make it easy to implement custom operations if the need arises. That way one has examples to look at when implementing new operations.

> why `update` and `pop` methods of `tinydb.utils.FrozenDict` write like this?

That's in order to make the static type analsis of mypy happy. Changing it will result in an type check error:

```
Incompatible types in assignment (expression has type "Callable[[FrozenDict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as overloaded function)
```

That's because the function signature of `_immutable` doesn't match the expected function signature of `update` and `pop`.
