### ISSUE TITLE
Question: how to prevent JSONDecodeError

### ISSUE THREAD

**Issue by rafaellehmkuhl** [msiemens/tinydb#341]
I have a platform using TinyDB and sometimes two scripts run over the same database file, leading to JSONDecodeError in no time. Is there any way of blocking the access of a second script to a database file already being used, or maybe someway to prevent this error if this situation happens?

**Comment by msiemens** [comment]
Hey @rafaellehmkuhl, TinyDB doesn't multi-threaded or multi-process access to the database file. An option would be to have a small service that is responsible for database access and is the only process that accesses the database file. Otherwise I think one could try to write a custom storage that implements some form of file-based locking (making sure that a lock file can be created/opened using [exclusive access](https://stackoverflow.com/questions/186202/what-is-the-best-way-to-open-a-file-for-exclusive-access-in-python)). But that's beyond the scope of TinyDB itself.

**Comment by rafaellehmkuhl** [comment]
I really liked the idea of controlling access externally @msiemens , thank you!

And thank you also for the library, it's great!
