### ISSUE TITLE
Use regex to search data from the list?

### ISSUE THREAD

**Issue by yuban10703** [msiemens/tinydb#360]
I took a look at the document, does tinydb not support using regex to search for data from the list?
If possible, can you explain how to use it,Thank you.

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/103224775-51544800-4963-11eb-8311-43849eb857b4.png)

**Comment by yuban10703** [comment]
I want to search the data in the tags list by regex
 :flushed:

**Comment by msiemens** [comment]
Hey @yuban10703,

you can use a custom test function to accomplish this:

```python
def matches_regex(values, pattern):
    return any(re.match(pattern, value) for value in values)

db.contains(Query().value.test(matches_regex, '.*?c'))
```

This will return all documents that have a `value` entry that matches the regex `.*?`.

Does this accomplish what you want?

**Comment by yuban10703** [comment]
Thanks, is there any hope that this feature can be added directly to the api?

:satisfied:
--

**Comment by msiemens** [comment]
> is there any hope that this feature can be added directly to the api?

To be honest, I don't really think this should be added into the TinyDB core. There are a _lot_ of operations one could use with list data but trying to add all of them isn't really feasable because it's hard to decide where to stop. One always can implement a custom test function that accomplished what is needed without modifying the TinyDB core.

---

On a second thought, TinyDB _does_ support querying list data — if it contains `dict` objects:

```python
from tinydb import TinyDB, Query
from tinydb.storages import MemoryStorage

tmpDB = TinyDB(storage=MemoryStorage)
Q = Query()

tmpDB.insert({"name":"aaa","tags":[{"name": "aac"},{"name": "bbc"}, {"name": "ccd"}]})
tmpDB.insert({"name":"bbb","tags":[{"name": "d"}]})
print(tmpDB.search(Q.tags.any(Q.name.matches('.*?c'))))
```

Using `.any` and `.all` one can use regular queries to query for documents with specified list entries. Maybe that's an option for you.

**Comment by yuban10703** [comment]
Thank you for solving my problem
:satisfied:
--
