### ISSUE TITLE
UTF-8 coding problem

### ISSUE THREAD

**Issue by supershevchenko** [msiemens/tinydb#369]
How to make the data UTF-8 encoding, using jsonstorage class parameters does not work。

**Comment by supershevchenko** [comment]
table.insert({'language':'chinese','content':'我是中文'});

the result:
{"config": {"1": {"language": "chinese", "content": "\u6211\u662f\u4e2d\u6587"}}}

I hope :
{"config": {"1": {"language": "chinese", "content": "我是中文"}}}

**Comment by msiemens** [comment]
Hey @supershevchenko,

this is because TinyDB uses the Python JSON serializer which by default encodes strings as ASCII. To disable this, you can pass `ensure_ascii=False` to the TinyDB constructor:

```python
from tinydb import TinyDB, Query

db = TinyDB('test.db', ensure_ascii=False)
db.insert({'language': 'chinese', 'content': '我是中文'})
```

In the same way you can pass all other arguments that [`json.dump`](https://docs.python.org/3.9/library/json.html#json.dumps) expects.

Does this help?

**Comment by supershevchenko** [comment]
I understand

**Comment by supershevchenko** [comment]
@msiemens
yes ,I understand,think you!
