### ISSUE TITLE
Count distinct elements

### ISSUE THREAD

**Issue by vio-codes** [msiemens/tinydb#370]
I'm looking for a way to easily see in my date how many distinct element I have.

**Comment by vio-codes** [comment]
Is there a way can count all the distance elements in the db for example:

db.count(distinct(Fruit.name))

Returning the number of distinct fruit names?

**Comment by msiemens** [comment]
Hey @vio-codes, that's an interesting case! TinyDB itself doesn't have an operation for this. Instead you'd have to use something like this:

```python
len(set([doc['name'] for doc in db.all()]))
```

I agree that it would be useful to have this for some cases, but I'm unsure whether we can add this without changing the architecture and design of TinyDB in possibly breaking ways. This is because the design of TinyDB doesn't really support this use case. For example, the query system only tells us if a document matches the query, but does _not_ allow us to extract specific fields from documents. Changing this would be a _major_ change. So we'd have to add a completely separate system to extract fields from documents which I don' really want to do.

**Comment by vio-codes** [comment]
Thank you very much for the answer.
I'll try to use the code provided by you.
