### ISSUE TITLE
Unable to query for key named as 'test'

### ISSUE THREAD

**Issue by bhargavimohan** [msiemens/tinydb#373]
The following snippet gives an error  `TypeError: 'bool' object is not callable`

> from tinydb import TinyDB, Query,where
> from tinydb.operations import delete
> db = TinyDB('db.json')
> 
> table = db.table('Initializedtables')
> table.insert({"test": "value"})  
> ch = Query()
> table.search(ch["test"] == "value")

I believe this is due to the conflicting method named "test" in the Query class, In such cases, how to deal with this?

**Comment by msiemens** [comment]
Hey @bhargavimohan! You're correct about the conflict with the `Query().test` method. The intended way around this issue was to use `Query()['test']` like you did – only that there was a bug that prevented this very alternative from working properly. A fix for this has now been released in TinyDB v4.4 🙂

**Comment by msiemens** [comment]
Can you test the new release to verify your code works now?

**Comment by bhargavimohan** [comment]
Hey @msiemens ! It works without any error now. Thanks for the help.
