### ISSUE TITLE
Very slow to save

### ISSUE THREAD

**Issue by mxd008** [msiemens/tinydb#397]
Very slow to save
You can refer to this https://github.com/5elenay/datagoose
Can be saved regularly or manually

**Comment by liukun** [comment]
As the README said https://github.com/msiemens/tinydb#using-middlewares , you can
```python
from tinydb.storages import JSONStorage
from tinydb.middlewares import CachingMiddleware
db = TinyDB('/path/to/db.json', storage=CachingMiddleware(JSONStorage))
db.storage.flush() # force save
```

**Comment by msiemens** [comment]
The comparison with datagoose is interesting as they are using [orjson](https://github.com/ijl/orjson) for reading/writing JSON which uses Rust to speed up the parsing. TinyDB on the other hand doesn't use any third-party modules at all and relies on the Python standard library only. And not only that, but datagoose doesn't write to disk at all by default which again is different from TinyDB which writes data to disk after every write operation. This has a performance penalty but makes sure that one doesn't lose data because forgetting to call `save()`.

But: it's not too hard to [create a new storage backend](https://tinydb.readthedocs.io/en/latest/extend.html#write-a-custom-storage) which would use orjson to get better performance when reading/writing larger datasets. And by using the already mentioned `CachingMiddleware` would make TinyDB only write to disk after a specified number of write operations which would make it very close to how datagoose works 🙂
