### ISSUE TITLE
rename Keys

### ISSUE THREAD

**Issue by hebabaze** [msiemens/tinydb#418]
i want to rename keys with saving the dictionary keys order , i try some things like that but it's not successful

from collections import OrderedDict
```
def rename(old , to):
    def transform(doc):
      doc=OrderedDict(doc)
      L=list(doc.keys())
      t=L.index(old)
      print(doc)
      doc[to] = doc.pop(old, None)
      print(doc)
      print(doc.keys())
      for x in L[t+1:]:
        doc.move_to_end(x)
      doc=dict(doc)
    return transform
```

**Comment by msiemens** [comment]
Basically, in your code you call `dict(doc)` which throws away the order information. But: it would be discarded anyway when TinyDB tries to store it. This is because while TinyDB accepts anything that looks like a `dict`, it always stores the data as a `dict`. Storage mechanisms like JSON don't support keeping the order of keys anyway, at least not without customization.

**Comment by msiemens** [comment]
Closing this issue as TinyDB doesn't support keeping dictionary order by its design. It's not possible to enforce that all storage backends that work with TinyDB (e.g. in custom extensions) have support to keep the dictionary order when reading the data.
