### ISSUE TITLE
Instantiated TinyDB object returns False?

### ISSUE THREAD

**Issue by JBloss1517** [msiemens/tinydb#419]
This caught me by surprise and I wanted to check if this was the intended behavior (or if I am missing something entirely). I was expecting a non-empty object to return `True`, but found that the `TinyDB` object returns False. Here is a minimal example showing what I am referring to:
```python
from tinydb import TinyDB

db = TinyDB("test.json")
print(db) # prints <TinyDB tables=[], tables_count=0, default_table_documents_count=0, all_tables_documents_count=[]>
print(bool(db)) # prints False
```

In my code I was trying to do something like:
```python
from tinydb import TinyDB

db = TinyDB("test.json")
Active_Structure = db.table("Structure1")
if Active_Structure:
    # do something 
    # This never gets run
else:
    # raise error
    # This always get run
```

but it was always falling back to the `else` since `bool(TinyDB)` or `bool(Table)` both return False

**Comment by eugene-eeo** [comment]
This is a result of how Python evaluates booleans.
When you do `if x: ...`, Python has to check if x is "truthy", i.e. whether `bool(x)` is True.
Internally, `bool(x)`:

1. first checks if `x` has a `__bool__` magic method -- if so, it returns `x.__bool__()`.
2. failing that, it then checks if `x` has a `__len__` magic method, and returns `bool(int(x.__len__()))` instead.

Perhaps it's a bit too simple, but that was what I observed playing around with classes in the REPL.
Anyways, your tables are probably empty (`Table.__len__` gives the number of documents in the table), and that's why the TinyDB() object return False.

**Comment by msiemens** [comment]
@eugene-eeo You're correct. To quote from the [Python documentation](https://docs.python.org/3/library/stdtypes.html#truth-value-testing):

> By default, an object is considered true unless its class defines either a `__bool__()` method that returns `False` or a `__len__()` method that returns zero, when called with the object.

So TinyDB doesn't do anything special to get this treatment other than implementing `__len__` which is needed for `len(db)` to work. And this also keeps TinyDB concistent with lists and dicts, which also return `False` when empty

**Comment by JBloss1517** [comment]
Ahh, that makes a ton of sense. Thank you both for your help.
