### ISSUE TITLE
Insert at index

### ISSUE THREAD

**Issue by PizzaRules668** [msiemens/tinydb#458]
How do you insert data at index, example
```
db.insert({data: "example"}, 0)
```
I was looking through the docs and I could not find anything.

**Comment by MrPigss** [comment]
[docs.](https://tinydb.readthedocs.io/en/latest/usage.html#:~:text=Also%20in%20some%20cases%20it%20may%20be%20useful%20to%20specify%20the%20document%20ID%20yourself%20when%20inserting%20data.%20You%20can%20do%20that%20by%20using%20the%20Document%20class%3A)

You have to pas a Document instead of a dict if you want to assign the id yourself.
Also inserting with an id that already exists results in an `assertionError doc_id {id} already exists.`

Use upsert if you want to update if it exists and insert if not.

Does this solve your question?

**Comment by msiemens** [comment]
@PizzaRules668 There is not quite a concept of indexes in TinyDB, at least not in the sense of an array where the index is an offset for that array. TinyDB instead has document IDs which uniquely indentify the documents stored in TinyDB.

To insert a document with a custom ID, you can wrap it in `tinydb.table.Document` class, as @MrPigss already mentioned:

```python
form tinydb.table import Document

db.insert(Document({'data': 'example'}, 1))
```

**Comment by PizzaRules668** [comment]
Alright thanks for the help. Sorry for not responding earlier

**Comment by msiemens** [comment]
> Sorry for not responding earlier

No worries, I wasn't particularly quick to respond either 🙂
