### ISSUE TITLE
is it possible to encrypt DB file and add authentication?

### ISSUE THREAD

**Issue by jackywu** [msiemens/tinydb#562]
is it possible to encrypt DB file and add authentication for connection ?

**Comment by MrPigss** [comment]
Definitely! 
You could try to write your own storage ([see docs](https://tinydb.readthedocs.io/en/latest/extend.html)).
It's fairly simple; you only need four methods.
`__init__`, `read`, `write`, and `close`.

Since you want to use authentication, I assume adding a password to the `__init__` function would be the easiest.
To actually encrypt the data, you can use something like [cryptography](https://pypi.org/project/cryptography/).
You can use [these docs](https://cryptography.io/en/latest/fernet/#using-passwords-with-fernet) to create a password.

1. On init, check if a password and/or key file exist (if not, create them).
2. Check the provided password (given through the `__init__` function).
3. If it's correct, finish initialization; otherwise, raise an error or something.
4. On every read, we'll decrypt; on every write, we'll encrypt.

Decrypting and encrypting on every read and write, respectively, will have a certain performance penalty, of course. 
You could also decrypt the file once on initialization and encrypt it during the close, but this will result in the file being readable on disk for as long as the program is active.

**Comment by msiemens** [comment]
As @MrPigss, it's possible to create a new storage that stores files on disk with encryption. Including such a storage within TinyDB core is out of scope for this project, though 🙂
