### ISSUE TITLE
itertools.ifilter() vs list comprehensions (Python2.x)

### ISSUE THREAD

**Issue by divanovGH** [msiemens/tinydb#79]
I think you need to use iterators. It's faster than lists.

**Comment by eugene-eeo** [comment]
You mean, generator comprehensions?

**Comment by divanovGH** [comment]
Yes. itertools.ifilter() or equivalent - generator expression

**Comment by msiemens** [comment]
@divanovGH Could you point to a specific function/code snippet where you think this would improve performance?

**Comment by divanovGH** [comment]
https://github.com/msiemens/tinydb/blob/master/tinydb/database.py#L368

**Comment by divanovGH** [comment]
https://github.com/msiemens/tinydb/blob/master/tinydb/database.py#L396-L398

**Comment by divanovGH** [comment]
https://github.com/msiemens/tinydb/blob/master/tinydb/database.py#L275

**Comment by msiemens** [comment]
I'm pretty sure that iterators aren't simply "faster than lists". But let's go case by case:

https://github.com/msiemens/tinydb/blob/master/tinydb/database.py#L368:

```python
elements = [element for element in self.all() if cond(element)]
```

Here we specifically want a list because 1) that's what the public API defines and 2) the result is stored in the query cache where a generator wouldn't make sense.

https://github.com/msiemens/tinydb/blob/master/tinydb/database.py#L396-L398:

```python
for element in self.all():
    if cond(element):
        return element
```

Here it could make sense to use generators so we don't have an intermediate list of values. But in a quick benchmark I did, there was no performance difference between this version and a generator based one.

https://github.com/msiemens/tinydb/blob/master/tinydb/database.py#L275: 

```python
return list(itervalues(self._read()))
```

Same as the first example: We want a list because that's what we want to return to the users. Changing the public API requires to release a new major version and I don't see how that would be justified.

**Comment by divanovGH** [comment]
Ok
